version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y docker.io || tail -n 100 /var/log/apt/term.log
            sudo apt-get clean
      - run:
          name: Build Docker image
          command: |
            docker build -t webapp-julie .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker tag webapp-julie $DOCKER_USER/webapp-julie:latest
            docker push $DOCKER_USER/webapp-julie:latest
      - run:
          name: Run and Test Container
          command: |
            docker run -d -p 5000:5000 webapp-julie
            for i in {1..30}; do
                if curl --fail http://127.0.0.1:5000; then
                    echo "Application is ready"
                    exit 0
                fi
                echo "Waiting for the application to be ready..."
                sleep 1
            done
            echo "Application did not start in time"
            exit 1
      - run:
          name: Install Python dependencies inside the container
          command: |
            docker exec webapp-julie pip install -r /app/requirements.txt
      - run:
          name: Run tests with pytest inside the container
          command: |
            docker exec webapp-julie pytest /app/test.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build